---
title: "Gov 50 Final Project"
author: "Rebecca Buehler"
description: "The Prevalence of 'Women and Children First' in Humanitarian Media"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I am planning to create a data visualization for my senior thesis. My thesis is an investigation of gender essentialisms in humanitarian media, or our tendency to portray civilian women as vulnerable victims and civilian men as violent perpetrators. These essentialisms are prevalent even though innocent men and boys (noncombatants) are twice as likely to die as a result of violent conflict. I will critique the "women and children first" narrative as it appears explicitly in text and implicitly in imagery. I will do this by identifying the gap between reality (the proportion of civilian victims that are male) and representation (the proportion of humanitarian media that centers male vulnerability and victimization). The central case study of my thesis is the conflict and humanitarian crisis in the Tigray region of Ethiopia. 

I would like to use this project to create a data visualization for a portion of the data that I will collect this semester. Ideally, I would like to represent the gap between representation and reality. I already have some gender-disaggregated data on victimization from ACLED. I will be coding text and imagery from UN agencies and international NGOs to gather representation data in the coming months. If I do not have sufficient data on representation by Milestone 3, I will only create a visualization with the ACLED data. 

## Research proposal

Gender disaggregated casualty data from the war in Tigray is not available. The ACLED data (https://epo.acleddata.com/data/) distinguishes violence that specifically targeted women, without doing the same for violence that targeted men. It also provides information on type of violence, perpetrating groups, targeted groups, and fatalities, among other categories. Using the available data from ACLED and the existing literature on male victimization, I will seek to answer the following research questions:

1. What proportion of the violence during the war in Tigray targeted civilians? Of that violence, what proportion was lethal violence? How many total civilian casualties occurred during the war?
2. What proportion of the violence during the war in Tigray targeted women (female civilians)? Of that violence, what proportion was lethal violence? How many fatalities occurred during violent events that targeted women?
3. Based on the findings of Ormhaug et al. 2009, what is the estimated difference in male and female civilian casualties in the war in Tigray?

I hypothesize that the proportion of lethal violence that specifically targets women will be smaller than the proportion of lethal violence that targets civilians in general. Existing literature demonstrates that female civilians suffer disproportionately from conflict-related sexual violence, while male civilians suffer disproportionately from all other forms of conflict-related violence. This data set distinguishes between event and sub-event type, with sexual violence as a category. Therefore, I estimate that the majority of events where women were targeted will be coded as sexual violence. 

Additionally, I hypothesize that based on the estimates of Ormhaug et al., male civilians will be disproportionately affected by lethal violence in Tigray.The existing literature on gendered victimization in conflict contexts demonstrates that male civilians are twice as likely to die as female civilians (Ormhaug et al.). Using this estimate, I hypothesize that the proportion of civilian casualities, and subsequently the estimated proportion of those that are men, will be greater than the number of women targeted by lethal violence. 

My variables of interest are type of violence and civilian group targeted. My outcome of interest in the number of fatalities. I am waiting to hear back from ACLED for a codebook for this data set. 



